# Generated by Django 4.1.7 on 2023-02-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("unique_hash", models.TextField()),
                ("tx_hash", models.TextField()),
                ("media_url", models.TextField()),
                ("owner", models.CharField(max_length=46)),
            ],
        ),
    ]
